-- reversible: no
-- backup-required: initial schema; restore is the rollback path
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TYPE traffic_reset_strategy AS ENUM ('NO_RESET', 'DAY', 'WEEK', 'MONTH');
CREATE TYPE subscription_source AS ENUM ('trial', 'purchase', 'admin', 'promo');
CREATE TYPE subscription_status AS ENUM ('provisioning', 'active', 'grace', 'expired', 'revoked', 'provisioning_failed');
CREATE TYPE account_kind AS ENUM ('user', 'revenue', 'provider_clearing', 'referral_expense', 'promo_expense', 'refund_pool', 'adjustment');
CREATE TYPE transaction_type AS ENUM ('purchase', 'topup', 'refund', 'referral_reward', 'referral_reversal', 'promo_bonus', 'adjustment', 'plan_change_credit');
CREATE TYPE transaction_status AS ENUM ('completed', 'reversed');
CREATE TYPE invoice_kind AS ENUM ('purchase', 'topup', 'plan_change');
CREATE TYPE invoice_status AS ENUM ('pending', 'paid', 'expired', 'canceled', 'underpaid');
CREATE TYPE referral_status AS ENUM ('pending', 'converted', 'rejected');
CREATE TYPE promocode_type AS ENUM ('discount_percent', 'discount_fixed', 'bonus_days', 'bonus_balance');
CREATE TYPE admin_role AS ENUM ('admin', 'operator');
CREATE TYPE broadcast_status AS ENUM ('draft', 'scheduled', 'running', 'paused', 'done', 'canceled', 'failed');

CREATE TABLE admins (id uuid PRIMARY KEY DEFAULT uuidv7(), email citext NOT NULL UNIQUE, password_hash text NOT NULL, role admin_role NOT NULL, totp_secret_enc text, totp_enabled boolean NOT NULL DEFAULT false, telegram_id bigint, is_active boolean NOT NULL DEFAULT true, last_login_at timestamptz, failed_logins integer NOT NULL DEFAULT 0, locked_until timestamptz, deleted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE settings (key text PRIMARY KEY, value jsonb NOT NULL, is_secret boolean NOT NULL DEFAULT false, updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES admins(id));
CREATE TABLE panels (id smallint PRIMARY KEY CHECK (id = 1), base_url text NOT NULL, api_token_enc text NOT NULL, webhook_secret_enc text, last_ok_at timestamptz, last_error text, version text);
CREATE TABLE users (id uuid PRIMARY KEY DEFAULT uuidv7(), telegram_id bigint NOT NULL UNIQUE, username text, first_name text, language char(2) NOT NULL, referral_code char(8) NOT NULL UNIQUE, referrer_id uuid REFERENCES users(id) ON DELETE SET NULL, email text, bot_blocked_at timestamptz, marketing_opt_out boolean NOT NULL DEFAULT false, is_banned boolean NOT NULL DEFAULT false, trial_used_at timestamptz, last_seen_at timestamptz, anonymized_at timestamptz, first_connected_at timestamptz, pending_promocode_id uuid, notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE channel_identities (id uuid PRIMARY KEY DEFAULT uuidv7(), user_id uuid NOT NULL REFERENCES users(id), channel text NOT NULL CHECK (channel = 'telegram'), external_id text NOT NULL, meta jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(channel, external_id));
CREATE TABLE panel_users (user_id uuid PRIMARY KEY REFERENCES users(id), panel_id smallint NOT NULL DEFAULT 1 REFERENCES panels(id), panel_uuid uuid NOT NULL, panel_username text NOT NULL, short_uuid text NOT NULL, subscription_url text NOT NULL, panel_status text NOT NULL, used_traffic_bytes bigint NOT NULL DEFAULT 0, traffic_limit_bytes bigint NOT NULL DEFAULT 0, expire_at_panel timestamptz, hwid_device_limit integer, squads uuid[] NOT NULL DEFAULT '{}', conflict boolean NOT NULL DEFAULT false, synced_at timestamptz, sync_error text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(panel_id, panel_uuid));
CREATE TABLE plans (id uuid PRIMARY KEY DEFAULT uuidv7(), slug text NOT NULL UNIQUE, name jsonb NOT NULL, description jsonb NOT NULL DEFAULT '{}', duration_days integer NOT NULL CHECK (duration_days > 0), traffic_limit_bytes bigint NOT NULL DEFAULT 0, traffic_reset_strategy traffic_reset_strategy NOT NULL DEFAULT 'NO_RESET', device_limit integer NOT NULL DEFAULT 0, squads uuid[] NOT NULL, price_minor bigint NOT NULL CHECK (price_minor >= 0), currency char(3) NOT NULL DEFAULT 'RUB', price_overrides jsonb NOT NULL DEFAULT '{}', is_public boolean NOT NULL DEFAULT true, is_active boolean NOT NULL DEFAULT true, sort_order integer NOT NULL DEFAULT 100, deleted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE subscriptions (id uuid PRIMARY KEY DEFAULT uuidv7(), user_id uuid NOT NULL REFERENCES users(id), plan_id uuid REFERENCES plans(id), source subscription_source NOT NULL, status subscription_status NOT NULL, starts_at timestamptz NOT NULL, expires_at timestamptz NOT NULL, traffic_limit_bytes bigint NOT NULL, device_limit integer NOT NULL, squads uuid[] NOT NULL, traffic_reset_strategy traffic_reset_strategy NOT NULL, notified jsonb NOT NULL DEFAULT '{}', revoked_reason text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE accounts (id uuid PRIMARY KEY DEFAULT uuidv7(), kind account_kind NOT NULL, user_id uuid REFERENCES users(id), provider text, currency char(3) NOT NULL, balance_minor bigint NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE invoices (id uuid PRIMARY KEY DEFAULT uuidv7(), user_id uuid NOT NULL REFERENCES users(id), kind invoice_kind NOT NULL, plan_id uuid REFERENCES plans(id), provider text NOT NULL, status invoice_status NOT NULL, amount_minor bigint NOT NULL CHECK (amount_minor > 0), currency char(3) NOT NULL, provider_amount numeric(20,8), provider_currency text, fx_rate numeric(20,8), discount_minor bigint NOT NULL DEFAULT 0, promocode_id uuid, provider_invoice_id text, payment_url text, provider_payload jsonb NOT NULL DEFAULT '{}', expires_at timestamptz NOT NULL, paid_at timestamptz, receipt jsonb, idempotency_key text NOT NULL UNIQUE, numeric_id bigint GENERATED ALWAYS AS IDENTITY UNIQUE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE transactions (id uuid PRIMARY KEY DEFAULT uuidv7(), user_id uuid NOT NULL REFERENCES users(id), type transaction_type NOT NULL, status transaction_status NOT NULL, amount_minor bigint NOT NULL CHECK (amount_minor >= 0), currency char(3) NOT NULL, provider text, invoice_id uuid REFERENCES invoices(id), parent_id uuid REFERENCES transactions(id), subscription_id uuid REFERENCES subscriptions(id), plan_id uuid REFERENCES plans(id), refunded_minor bigint NOT NULL DEFAULT 0, reason text, actor_admin_id uuid REFERENCES admins(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE ledger_entries (id uuid PRIMARY KEY DEFAULT uuidv7(), transaction_id uuid NOT NULL REFERENCES transactions(id), debit_account_id uuid NOT NULL REFERENCES accounts(id), credit_account_id uuid NOT NULL REFERENCES accounts(id), amount_minor bigint NOT NULL CHECK (amount_minor > 0), currency char(3) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CHECK (debit_account_id <> credit_account_id));
CREATE TABLE payment_events (id uuid PRIMARY KEY DEFAULT uuidv7(), provider text NOT NULL, external_id text NOT NULL, invoice_id uuid REFERENCES invoices(id), type text NOT NULL, raw jsonb NOT NULL, headers jsonb NOT NULL, signature_ok boolean NOT NULL, processed_at timestamptz, process_error text, received_at timestamptz NOT NULL DEFAULT now(), UNIQUE(provider, external_id));
CREATE TABLE payment_providers (code text PRIMARY KEY, enabled boolean NOT NULL DEFAULT false, display_name jsonb NOT NULL, sort_order integer NOT NULL DEFAULT 100, config_enc text, supports_receipts boolean NOT NULL DEFAULT false, last_healthcheck_at timestamptz, last_healthcheck_ok boolean, last_healthcheck_error text, updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES admins(id));
CREATE TABLE referral_attributions (id uuid PRIMARY KEY DEFAULT uuidv7(), referee_id uuid NOT NULL UNIQUE REFERENCES users(id), referrer_id uuid NOT NULL REFERENCES users(id), source text NOT NULL, code char(8), status referral_status NOT NULL, converted_transaction_id uuid REFERENCES transactions(id), rejected_reason text, created_at timestamptz NOT NULL DEFAULT now(), converted_at timestamptz, CHECK (referee_id <> referrer_id));
CREATE TABLE referral_rewards (id uuid PRIMARY KEY DEFAULT uuidv7(), attribution_id uuid NOT NULL REFERENCES referral_attributions(id), transaction_id uuid NOT NULL REFERENCES transactions(id), source_transaction_id uuid NOT NULL UNIQUE REFERENCES transactions(id), amount_minor bigint NOT NULL, hold_until timestamptz, status text NOT NULL CHECK (status IN ('held','released','reversed')), reversal_transaction_id uuid REFERENCES transactions(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE promocodes (id uuid PRIMARY KEY DEFAULT uuidv7(), code text NOT NULL, type promocode_type NOT NULL, value bigint NOT NULL, max_uses integer, max_uses_per_user integer NOT NULL DEFAULT 1, used_count integer NOT NULL DEFAULT 0, valid_from timestamptz, valid_until timestamptz, plan_ids uuid[] NOT NULL DEFAULT '{}', first_purchase_only boolean NOT NULL DEFAULT false, min_amount_minor bigint NOT NULL DEFAULT 0, is_active boolean NOT NULL DEFAULT true, deleted_at timestamptz, created_by uuid REFERENCES admins(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE promocode_redemptions (id uuid PRIMARY KEY DEFAULT uuidv7(), promocode_id uuid NOT NULL REFERENCES promocodes(id), user_id uuid NOT NULL REFERENCES users(id), invoice_id uuid REFERENCES invoices(id), transaction_id uuid REFERENCES transactions(id), applied_value_minor bigint, applied_days integer, status text NOT NULL CHECK (status IN ('reserved','applied','released')), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE audit_log (id uuid PRIMARY KEY DEFAULT uuidv7(), actor_admin_id uuid REFERENCES admins(id), actor_type text NOT NULL, action text NOT NULL, entity text NOT NULL, entity_id text, before jsonb, after jsonb, reason text, ip inet, user_agent text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE notification_log (id uuid PRIMARY KEY DEFAULT uuidv7(), user_id uuid NOT NULL REFERENCES users(id), event text NOT NULL, subscription_id uuid REFERENCES subscriptions(id), dedup_key text NOT NULL, channel text NOT NULL DEFAULT 'telegram', status text NOT NULL CHECK (status IN ('sent','failed','skipped_blocked','skipped_opt_out')), error text, sent_at timestamptz, UNIQUE(user_id, dedup_key));
CREATE TABLE broadcasts (id uuid PRIMARY KEY DEFAULT uuidv7(), title text NOT NULL, content jsonb NOT NULL, segment jsonb NOT NULL, scheduled_at timestamptz, status broadcast_status NOT NULL, total_count integer NOT NULL DEFAULT 0, sent_count integer NOT NULL DEFAULT 0, blocked_count integer NOT NULL DEFAULT 0, failed_count integer NOT NULL DEFAULT 0, created_by uuid NOT NULL REFERENCES admins(id), started_at timestamptz, finished_at timestamptz, deleted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE broadcast_deliveries (broadcast_id uuid NOT NULL REFERENCES broadcasts(id), user_id uuid NOT NULL REFERENCES users(id), status text NOT NULL CHECK (status IN ('sent','blocked','failed')), error text, sent_at timestamptz, PRIMARY KEY (broadcast_id, user_id));
CREATE TABLE locale_overrides (lang char(2) NOT NULL, namespace text NOT NULL, key text NOT NULL, value text NOT NULL, updated_by uuid REFERENCES admins(id), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (lang, namespace, key));
CREATE TABLE outbox_jobs (id uuid PRIMARY KEY DEFAULT uuidv7(), queue text NOT NULL, name text NOT NULL, payload jsonb NOT NULL, job_id text, published_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE setup_state (id smallint PRIMARY KEY CHECK (id = 1), completed boolean NOT NULL DEFAULT false, current_step text, data jsonb NOT NULL DEFAULT '{}', token_hash text, updated_at timestamptz NOT NULL DEFAULT now());

ALTER TABLE users ADD CONSTRAINT fk_users_pending_promocode FOREIGN KEY (pending_promocode_id) REFERENCES promocodes(id);
ALTER TABLE transactions ADD CONSTRAINT ux_transactions_invoice_p UNIQUE (invoice_id) DEFERRABLE INITIALLY IMMEDIATE;
CREATE UNIQUE INDEX ux_accounts_user_id_p ON accounts(user_id) WHERE kind = 'user';
CREATE UNIQUE INDEX ux_accounts_provider_p ON accounts(provider) WHERE kind = 'provider_clearing';
CREATE UNIQUE INDEX ux_subscriptions_one_live_p ON subscriptions(user_id) WHERE status IN ('provisioning','active','grace');
CREATE UNIQUE INDEX ux_invoices_provider_invoice ON invoices(provider, provider_invoice_id) WHERE provider_invoice_id IS NOT NULL;
CREATE UNIQUE INDEX ux_promocodes_code_upper ON promocodes(upper(code));
CREATE UNIQUE INDEX ux_referral_rewards_source ON referral_rewards(source_transaction_id);
CREATE INDEX ix_plans_public_active_p ON plans(sort_order) WHERE is_public AND is_active AND deleted_at IS NULL;
CREATE INDEX ix_subscriptions_expires_at_status ON subscriptions(expires_at, status);
CREATE INDEX ix_transactions_user_created ON transactions(user_id, created_at DESC);
CREATE INDEX ix_ledger_entries_transaction_id ON ledger_entries(transaction_id);
CREATE INDEX ix_payment_events_invoice_id ON payment_events(invoice_id);
CREATE INDEX ix_invoices_user_status ON invoices(user_id, status);
CREATE INDEX ix_audit_log_entity ON audit_log(entity, entity_id);
CREATE INDEX ix_audit_log_created_at ON audit_log(created_at);
CREATE INDEX ix_audit_log_actor ON audit_log(actor_admin_id);
CREATE INDEX ix_referral_attributions_referrer_status ON referral_attributions(referrer_id, status);
CREATE INDEX ix_outbox_jobs_unpublished_p ON outbox_jobs(created_at) WHERE published_at IS NULL;

CREATE OR REPLACE FUNCTION forbid_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'immutable table: %', TG_TABLE_NAME USING ERRCODE = '27000'; END; $$;
CREATE OR REPLACE FUNCTION transactions_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'transactions are immutable' USING ERRCODE = '27000'; END IF; IF to_jsonb(NEW) - ARRAY['status','refunded_minor'] <> to_jsonb(OLD) - ARRAY['status','refunded_minor'] THEN RAISE EXCEPTION 'transactions are immutable except status/refunded_minor' USING ERRCODE = '27000'; END IF; RETURN NEW; END; $$;
CREATE TRIGGER transactions_guard BEFORE UPDATE OR DELETE ON transactions FOR EACH ROW EXECUTE FUNCTION transactions_guard();
CREATE TRIGGER ledger_entries_immutable BEFORE UPDATE OR DELETE ON ledger_entries FOR EACH ROW EXECUTE FUNCTION forbid_mutation();
CREATE TRIGGER payment_events_immutable BEFORE UPDATE OR DELETE ON payment_events FOR EACH ROW EXECUTE FUNCTION forbid_mutation();
CREATE TRIGGER audit_log_immutable BEFORE UPDATE OR DELETE ON audit_log FOR EACH ROW EXECUTE FUNCTION forbid_mutation();
CREATE TRIGGER notification_log_immutable BEFORE UPDATE OR DELETE ON notification_log FOR EACH ROW EXECUTE FUNCTION forbid_mutation();

INSERT INTO panels (id, base_url, api_token_enc) VALUES (1, 'https://panel.invalid', '');
INSERT INTO setup_state (id) VALUES (1);
INSERT INTO payment_providers (code, display_name) VALUES
  ('yookassa', '{"ru":"ЮKassa","en":"YooKassa"}'), ('platega', '{"ru":"Platega","en":"Platega"}'), ('lava', '{"ru":"Lava","en":"Lava"}'), ('robokassa', '{"ru":"Robokassa","en":"Robokassa"}'), ('cryptobot', '{"ru":"CryptoBot","en":"CryptoBot"}'), ('stars', '{"ru":"Telegram Stars","en":"Telegram Stars"}');
INSERT INTO accounts (kind, currency) VALUES ('revenue','RUB'), ('referral_expense','RUB'), ('promo_expense','RUB'), ('refund_pool','RUB'), ('adjustment','RUB');
