-- Section 11.3.4: Robokassa's `InvId` is `numeric_id`, and the payment link
-- that carries it is built before the invoice row is written (section 11.2).
-- The API therefore takes the value from this column's own identity sequence
-- and inserts it, which `GENERATED ALWAYS` refuses. The values still come
-- from the one sequence and stay unique.
-- reversible: yes — ALTER TABLE invoices ALTER COLUMN numeric_id SET GENERATED ALWAYS;
ALTER TABLE invoices ALTER COLUMN numeric_id SET GENERATED BY DEFAULT;
